{{- if and .Values.server.enabled .Values.server.config.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.server.config.service.name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.server.config.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.server.config.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.server.config.service.name }}
                port:
                  number: {{ .Values.server.config.service.port }}
  {{- if .Values.server.config.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.server.config.ingress.host }}
      secretName: {{ .Values.server.config.ingress.tls.secretName }}
  {{- end }}
{{- end }}
