name: Build Agent
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd certeye-agent
        docker build . --file Dockerfile --tag quay.io/certeye/certeye-agent:v1.0.${{github.run_number}}
    - name: Save Image
      run: |
        docker save quay.io/certeye/certeye-agent:v1.0.${{github.run_number}} -o image.tar
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: docker-image
        path: image.tar

  docker-image-inspect:

    runs-on: ubuntu-latest
    needs: docker-build
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: docker-image
    - name: Docker Load
      run: |
        docker load < image.tar
    - name: Docker Inspect
      run: |
        docker image inspect quay.io/certeye/certeye-agent:v1.0.${{github.run_number}}

  docker-push:
    environment:
      name: dev
    runs-on: ubuntu-latest
    needs: [ docker-build, docker-image-inspect ]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: docker-image
    - name: Docker Load
      run: |
        docker load < image.tar
    - name: Docker Login
      env:
        QUAY_IO_ROBOT_PASSWORD: ${{ secrets.QUAY_IO_ROBOT_PASSWORD }}
        QUAY_IO_ROBOT_USER: ${{ secrets.QUAY_IO_ROBOT_USER }}
      run: |
        docker login -u='$QUAY_IO_ROBOT_USER' -p='$QUAY_IO_ROBOT_PASSWORD'
    - name: Docker Push
      run: |
        docker push quay.io/certeye/certeye-agent:v1.0.${{github.run_number}}
